// wordcloud2.js word list — Mathematics Münster mathematical terms
// Source: tagcloud_masked.csv (longest-match-first masking)
// Usage: WordCloud(document.getElementById('canvas'), { list: wordList });
var wordList =
[
  ["partial differential equation", 129],
  ["K-theory", 110],
  ["cohomology", 104],
  ["model order reduction", 101],
  ["artificial neural network", 83],
  ["curvature", 81],
  ["manifold", 68],
  ["moduli space", 47],
  ["machine learning", 41],
  ["homogenisation", 34],
  ["quantum field theory", 32],
  ["C*-algebra", 31],
  ["Langlands programme", 30],
  ["percolation", 28],
  ["stochastic gradient descent", 23],
  ["geodesic", 22],
  ["Phi^4 equation", 21],
  ["operator algebra", 21],
  ["amenable group", 21],
  ["optimal control", 19],
  ["stochastic analysis", 18],
  ["Einstein manifold", 18],
  ["deep learning", 18],
  ["scalar curvature", 17],
  ["random graph", 17],
  ["multiscale modelling", 17],
  ["error estimation", 17],
  ["curse of dimensionality", 17],
  ["regularity structure", 16],
  ["model theory", 16],
  ["inverse problem", 16],
  ["axiom of determinacy", 16],
  ["surrogate method", 15],
  ["Lie group", 15],
  ["entropy", 15],
  ["compactification", 15],
  ["topological recursion", 14],
  ["Riemannian manifold", 14],
  ["Ricci flow", 14],
  ["ReLU activation function", 14],
  ["random tessellation", 14],
  ["positive scalar curvature", 14],
  ["differential geometry", 14],
  ["large cardinal", 13],
  ["index theory", 13],
  ["crossed product", 13],
  ["cobordism", 13],
  ["numerical methods", 12],
  ["Kontsevich model", 11],
  ["étale cohomology", 11],
  ["convergence rate", 11],
  ["Adam optimizer", 11],
  ["Haagerup property", 10],
  ["group action", 10],
  ["derived category", 10],
  ["stochastic quantisation", 9],
  ["Shimura variety", 9],
  ["random polytope", 9],
  ["phase transition", 9],
  ["locally compact group", 9],
  ["geometric invariant theory", 9],
  ["free probability theory", 9],
  ["Dirac operator", 9],
  ["cardinal", 9],
  ["reductive group", 8],
  ["orbit equivalence", 8],
  ["motivic cohomology", 8],
  ["integrability", 8],
  ["G-shtuka", 8],
  ["fundamental group", 8],
  ["classifying space", 8],
  ["Borel conjecture", 8],
  ["algebraic group", 8],
  ["vector bundle", 7],
  ["topological space", 7],
  ["stratification", 7],
  ["Poincaré duality", 7],
  ["physics-informed neural network", 7],
  ["KK-theory", 7],
  ["kinetic equation", 7],
  ["interacting particle system", 7],
  ["Hamilton-Jacobi-Bellman equation", 7],
  ["groupoid", 7],
  ["Fraïssé limit", 7],
  ["Z-stability", 6],
  ["torus symmetry", 6],
  ["toric geometry", 6],
  ["Teichmüller theory", 6],
  ["surgery theory", 6],
  ["stochastic geometry", 6],
  ["stable infinity-category", 6],
  ["spectral sequence", 6],
  ["sheaf", 6],
  ["NIP field", 6],
  ["Monte Carlo method", 6],
  ["minimal hypersurface", 6],
  ["mean curvature", 6],
  ["mapping class group", 6],
  ["large deviation principle", 6],
  ["intersection theory", 6],
  ["Hecke algebra", 6],
  ["harmonic analysis", 6],
  ["geometric group theory", 6],
  ["general relativity", 6],
  ["forcing axiom", 6],
  ["fluid dynamics", 6],
  ["ergodic theory", 6],
  ["diffeomorphism group", 6],
  ["sharply 2-transitive group", 5],
  ["Schubert cell", 5],
  ["Riemannian shape space", 5],
  ["random walk", 5],
  ["parabolic Anderson model", 5],
  ["number theory", 5],
  ["noncommutative geometry", 5],
  ["KPZ equation", 5],
  ["Grassmannian", 5],
  ["geometric analysis", 5],
  ["Euler equations", 5],
  ["combinatorics", 5],
  ["characteristic class", 5],
  ["automorphism group", 5],
  ["abelian group", 5],
  ["wave equation", 4],
  ["WASEP", 4],
  ["von Neumann algebra", 4],
  ["torus", 4],
  ["Strebel differential", 4],
  ["spin structure", 4],
  ["sparse reconstruction", 4],
  ["Roe algebra", 4],
  ["Riemannian spline", 4],
  ["Riemannian metric", 4],
  ["randomly perforated domain", 4],
  ["prismatic cohomology", 4],
  ["polytope", 4],
  ["nonstationary ideal", 4],
  ["Newton stratum", 4],
  ["Moyal space", 4],
  ["Morley rank", 4],
  ["matroid", 4],
  ["Martin's Maximum", 4],
  ["Lorentzian geometry", 4],
  ["localized orthogonal decomposition", 4],
  ["lattice", 4],
  ["Kerr black hole", 4],
  ["Ising-Kac model", 4],
  ["inner model theory", 4],
  ["hypocoercivity", 4],
  ["hyperbolic group", 4],
  ["gravitational instanton", 4],
  ["Galois representation", 4],
  ["exact sequence", 4],
  ["enhanced dissipation", 4],
  ["Einstein equations", 4],
  ["deep operator learning", 4],
  ["crystalline cohomology", 4],
  ["Chern-Schwartz-MacPherson class", 4],
  ["black hole stability", 4],
  ["zeta function", 3],
  ["Witten conjecture", 3],
  ["tubular neighborhood", 3],
  ["training of neural networks", 3],
  ["stochastic porous medium equation", 3],
  ["stochastic block model", 3],
  ["statistical mechanics", 3],
  ["stationary point process", 3],
  ["sofic group", 3],
  ["Schur multiplier", 3],
  ["random walk in random environment", 3],
  ["random polynomial", 3],
  ["probability theory", 3],
  ["positive mass theorem", 3],
  ["percolation on groups", 3],
  ["optimal transport", 3],
  ["nuclear dimension", 3],
  ["motivic Chern class", 3],
  ["measure theory", 3],
  ["martingale", 3],
  ["local minimizer", 3],
  ["Lie algebra", 3],
  ["learning rate", 3],
  ["landscape analysis", 3],
  ["Kähler manifold", 3],
  ["Ising model", 3],
  ["invariant measure", 3],
  ["hyperuniformity", 3],
  ["Hodge theory", 3],
  ["henselian field", 3],
  ["Grothendieck group", 3],
  ["Gaussian multiplicative chaos", 3],
  ["Fröhlich polaron", 3],
  ["Ehrhart theory", 3],
  ["dynamical system", 3],
  ["coarse geometry", 3],
  ["Calabi-Yau manifold", 3],
  ["B-dR Grassmannian", 3],
  ["arithmetic group", 3],
  ["ALE space", 3],
  ["Woodin's axiom", 2],
  ["Wasserstein distance", 2],
  ["Verma module", 2],
  ["vanishing theorem", 2],
  ["transport equation", 2],
  ["symplectic group", 2],
  ["stochastic heat equation", 2],
  ["stochastic differential equation", 2],
  ["stable fields conjecture", 2],
  ["shape manifold", 2],
  ["sectional curvature", 2],
  ["scaling law", 2],
  ["saddle point", 2],
  ["rough path theory", 2],
  ["real algebraic geometry", 2],
  ["reaction-diffusion equation", 2],
  ["property Gamma", 2],
  ["positive scalar curvature cobordism category", 2],
  ["Poisson process", 2],
  ["paracontrolled calculus", 2],
  ["p-adic eigenform", 2],
  ["Ornstein theory", 2],
  ["Mumford conjecture", 2],
  ["motive", 2],
  ["moment map", 2],
  ["modular form", 2],
  ["McKendrick model", 2],
  ["Lyapunov function", 2],
  ["Lojasiewicz condition", 2],
  ["Landau-Pekar-Spohn conjecture", 2],
  ["inner amenability", 2],
  ["gradient flow", 2],
  ["functional analysis", 2],
  ["free group", 2],
  ["Fontaine-Wintenberger theorem", 2],
  ["financial derivative pricing", 2],
  ["feature engineering", 2],
  ["Farrell-Jones conjecture", 2],
  ["Euler-Maclaurin formula", 2],
  ["descriptive set theory", 2],
  ["CW complex", 2],
  ["cusp form", 2],
  ["Curie-Weiss model", 2],
  ["cup product", 2],
  ["conservation law", 2],
  ["compliance minimisation", 2],
  ["CAT(0) cube complex", 2],
  ["branched transport", 2],
  ["Boltzmann equation", 2],
  ["beta distribution", 2],
  ["Benamou-Brenier formula", 2],
  ["backward stochastic differential equation", 2],
  ["Arkhipov-Bezrukavnikov equivalence", 2],
  ["algebraic variety", 2],
  ["Zakai equation", 1],
  ["Yang-Mills problem", 1],
  ["Witt vector", 1],
  ["vortex sheet", 1],
  ["ultrafilter", 1],
  ["thin film equation", 1],
  ["tautological class", 1],
  ["symplectic manifold", 1],
  ["Sylvester problem", 1],
  ["strong completeness", 1],
  ["Stein factorization", 1],
  ["specific entropy", 1],
  ["simplicial complex", 1],
  ["scissors automorphism group", 1],
  ["Schwarzschild black hole", 1],
  ["Rayleigh-Taylor instability", 1],
  ["quasimorphism", 1],
  ["pseudofinite group", 1],
  ["property T", 1],
  ["probability measure", 1],
  ["p-adic Corlette-Simpson correspondence", 1],
  ["optimal stopping", 1],
  ["optimal matching problem", 1],
  ["multi-fidelity modelling", 1],
  ["Mullins-Sekerka equation", 1],
  ["moduli space of curves", 1],
  ["magnetic skyrmion", 1],
  ["log-gas free energy", 1],
  ["local system", 1],
  ["Lee-Yang zeros", 1],
  ["Kolmogorov PDE", 1],
  ["Keller-Segel system", 1],
  ["K3 surface", 1],
  ["Ito formula", 1],
  ["infinite-dimensional metric measure space", 1],
  ["hyperbolic space", 1],
  ["homological stability", 1],
  ["Holley-Stroock uniqueness method", 1],
  ["higher rho-invariant", 1],
  ["Harder-Narasimhan stratification", 1],
  ["handlebody group", 1],
  ["Gysin map", 1],
  ["Grove symmetry program", 1],
  ["Grothendieck-Witt group", 1],
  ["graph complex", 1],
  ["Galois group", 1],
  ["free-discontinuity problem", 1],
  ["fractional Brownian motion", 1],
  ["Fokker-Planck equation", 1],
  ["finite element method", 1],
  ["enhanced oil recovery", 1],
  ["elliptic curve", 1],
  ["DG cut cell method", 1],
  ["definable valuation", 1],
  ["cyclotomic spectrum", 1],
  ["cross-diffusion system", 1],
  ["Coulomb energy", 1],
  ["convex body", 1],
  ["concentration inequality", 1],
  ["Catalan numbers", 1],
  ["Casselman's problem", 1],
  ["Cartier module", 1],
  ["Burnside problem", 1],
  ["Bruhat-Tits building", 1],
  ["Black-Scholes PDE", 1],
  ["Bernoulli action", 1],
  ["Ax-Kochen-Ershov principle", 1],
  ["autoencoder", 1],
  ["algebraicity conjecture", 1],
  ["algebraic cycle", 1],
  ["adic space", 1]
]
;
